export const SET_PROFILE_PICTURE_REQUEST = 'SET_PROFILE_PICTURE_REQUEST'
export const SET_PROFILE_PICTURE_SUCCESS = 'SET_PROFILE_PICTURE_SUCCESS'
export const SET_PROFILE_PICTURE_FAILURE = 'SET_PROFILE_PICTURE_FAILURE'

export const POSTS_REQUEST = 'POSTS_REQUEST'
export const POSTS_SUCCESS = 'POSTS_SUCCESS'
export const POSTS_FAILURE = 'POSTS_FAILURE'

export const FRIENDS_REQUEST = 'FRIENDS_REQUEST'
export const FRIENDS_SUCCESS = 'FRIENDS_SUCCESS'
export const FRIENDS_FAILURE = 'FRIENDS_FAILURE'